# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 123xyz
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: naurkri-clone
# "service" is the name of this project. This will also be added to your AWS resource names.
service: naukri-clone

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  deploymentBucket:
    name: naukri-clone-test  

functions:
  api:
    handler: dist/app.handler
    events:
      - httpApi: "*"
